name: learn_supabase
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.8.1







dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.1
  
  # Riverpod dependencies
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # SharedPreferences
  shared_preferences: ^2.5.3
  
  # Routing
  go_router: ^16.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Riverpod code generation
  build_runner: ^2.4.13
  riverpod_generator: ^2.4.0





flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
